version: "3.7"

volumes:
  database_data:
  parallax:

networks:
  default:

services:
  db:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=parallax
      - POSTGRES_DB=parallax-auth
      - POSTGRES_PASSWORD=parallax
    ports:
      - '5433:5433'
    networks:
      - default

  parallax-auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/parallax-auth
    ports:
      - "8001:8001"
    expose:
      - 8001
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=parallax_auth.settings
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=parallax-auth
      - DB_USER=parallax
      - DB_PASSWORD=parallax
    links:
      - db
    depends_on:
      - db
    networks:
      - default
